---
- name: Install nginx
  yum: name={{ "nginx" if nginx.version == "latest" else "nginx-" + nginx.version}} state=present
  notify: restart nginx

- file: path=/etc/nginx/conf.d/{{ item }} state=absent
  with_items:
    - default.conf
    - example_ssl.conf
  notify: restart nginx

- name: Install nginx config file
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf backup=true validate='nginx -t -p %s'
  notify: restart nginx

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started
